from typing import List

class ClothingItem:
    def __init__(self, name: str, category: str, temp_range: tuple, styles: List[str], colors: List[str]):
        self.name = name
        self.category = category
        self.temp_range = temp_range
        self.styles = styles
        self.colors = colors

    def matches(self, temperature, style, color_preference=None):
        temp_ok = self.temp_range[0] <= temperature <= self.temp_range[1]
        style_ok = style in self.styles
        color_ok = True if color_preference is None else color_preference in self.colors
        return temp_ok and style_ok and color_ok

    def __str__(self):
        return f"{self.name} ({self.category})"

clothing_items = [
    ClothingItem("white hoodie", "top", (5, 19), ['casual'], ['white']),
    ClothingItem("beige hoodie", "top", (5, 19), ['casual'], ['beige']),
    ClothingItem("cream hoodie", "top", (5, 19), ['casual'], ['cream']),
    ClothingItem("light grey hoodie", "top", (5, 19), ['casual'], ['light grey']),
    ClothingItem("sky blue hoodie", "top", (5, 19), ['casual'], ['sky blue']),
    ClothingItem("black hoodie", "top", (5, 19), ['casual'], ['black']),
    ClothingItem("navy hoodie", "top", (5, 19), ['casual'], ['navy']),
    ClothingItem("charcoal hoodie", "top", (5, 19), ['casual'], ['charcoal']),
    ClothingItem("dark brown hoodie", "top", (5, 19), ['casual'], ['dark brown']),
    ClothingItem("deep green hoodie", "top", (5, 19), ['casual'], ['deep green']),
    ClothingItem("beige thick jeans", "bottom", (5, 19), ['casual'], ['beige']),
    ClothingItem("black thick jeans", "bottom", (5, 19), ['casual'], ['black']),
    ClothingItem("navy thick jeans", "bottom", (5, 19), ['casual'], ['navy']),
    ClothingItem("black boots", "shoes", (5, 19), ['casual'], ['black']),
    ClothingItem("white boots", "shoes", (5, 19), ['casual'], ['white']),
    ClothingItem("brown boots", "shoes", (5, 19), ['casual'], ['brown']),
    ClothingItem("white long-sleeve T-shirt", "top", (20, 27), ['casual'], ['white']),
    ClothingItem("beige long-sleeve T-shirt", "top", (20, 27), ['casual'], ['beige']),
    ClothingItem("cream long-sleeve T-shirt", "top", (20, 27), ['casual'], ['cream']),
    ClothingItem("light grey long-sleeve T-shirt", "top", (20, 27), ['casual'], ['light grey']),
    ClothingItem("sky blue long-sleeve T-shirt", "top", (20, 27), ['casual'], ['sky blue']),
    ClothingItem("black long-sleeve T-shirt", "top", (20, 27), ['casual'], ['black']),
    ClothingItem("navy long-sleeve T-shirt", "top", (20, 27), ['casual'], ['navy']),
    ClothingItem("charcoal long-sleeve T-shirt", "top", (20, 27), ['casual'], ['charcoal']),
    ClothingItem("dark brown long-sleeve T-shirt", "top", (20, 27), ['casual'], ['dark brown']),
    ClothingItem("deep green long-sleeve T-shirt", "top", (20, 27), ['casual'], ['deep green']),
    ClothingItem("beige jeans", "bottom", (20, 27), ['casual'], ['beige']),
    ClothingItem("black jeans", "bottom", (20, 27), ['casual'], ['black']),
    ClothingItem("navy jeans", "bottom", (20, 27), ['casual'], ['navy']),
    ClothingItem("black sneakers", "shoes", (20, 27), ['casual'], ['black']),
    ClothingItem("white sneakers", "shoes", (20, 27), ['casual'], ['white']),
    ClothingItem("brown sneakers", "shoes", (20, 27), ['casual'], ['brown']),
    ClothingItem("white short-sleeve T-shirt", "top", (28, 40), ['casual'], ['white']),
    ClothingItem("beige short-sleeve T-shirt", "top", (28, 40), ['casual'], ['beige']),
    ClothingItem("cream short-sleeve T-shirt", "top", (28, 40), ['casual'], ['cream']),
    ClothingItem("light grey short-sleeve T-shirt", "top", (28, 40), ['casual'], ['light grey']),
    ClothingItem("sky blue short-sleeve T-shirt", "top", (28, 40), ['casual'], ['sky blue']),
    ClothingItem("black short-sleeve T-shirt", "top", (28, 40), ['casual'], ['black']),
    ClothingItem("navy short-sleeve T-shirt", "top", (28, 40), ['casual'], ['navy']),
    ClothingItem("charcoal short-sleeve T-shirt", "top", (28, 40), ['casual'], ['charcoal']),
    ClothingItem("dark brown short-sleeve T-shirt", "top", (28, 40), ['casual'], ['dark brown']),
    ClothingItem("deep green short-sleeve T-shirt", "top", (28, 40), ['casual'], ['deep green']),
    ClothingItem("beige cotton shorts", "bottom", (28, 40), ['casual'], ['beige']),
    ClothingItem("black cotton shorts", "bottom", (28, 40), ['casual'], ['black']),
    ClothingItem("navy cotton shorts", "bottom", (28, 40), ['casual'], ['navy']),
    ClothingItem("black canvas sneakers", "shoes", (28, 40), ['casual'], ['black']),
    ClothingItem("white canvas sneakers", "shoes", (28, 40), ['casual'], ['white']),
    ClothingItem("brown canvas sneakers", "shoes", (28, 40), ['casual'], ['brown']),
    ClothingItem("white fleece jacket", "top", (5, 19), ['sporty'], ['white']),
    ClothingItem("beige fleece jacket", "top", (5, 19), ['sporty'], ['beige']),
    ClothingItem("cream fleece jacket", "top", (5, 19), ['sporty'], ['cream']),
    ClothingItem("light grey fleece jacket", "top", (5, 19), ['sporty'], ['light grey']),
    ClothingItem("sky blue fleece jacket", "top", (5, 19), ['sporty'], ['sky blue']),
    ClothingItem("black fleece jacket", "top", (5, 19), ['sporty'], ['black']),
    ClothingItem("navy fleece jacket", "top", (5, 19), ['sporty'], ['navy']),
    ClothingItem("charcoal fleece jacket", "top", (5, 19), ['sporty'], ['charcoal']),
    ClothingItem("dark brown fleece jacket", "top", (5, 19), ['sporty'], ['dark brown']),
    ClothingItem("deep green fleece jacket", "top", (5, 19), ['sporty'], ['deep green']),
    ClothingItem("beige thermal joggers", "bottom", (5, 19), ['sporty'], ['beige']),
    ClothingItem("black thermal joggers", "bottom", (5, 19), ['sporty'], ['black']),
    ClothingItem("navy thermal joggers", "bottom", (5, 19), ['sporty'], ['navy']),
    ClothingItem("black running shoes", "shoes", (5, 19), ['sporty'], ['black']),
    ClothingItem("white running shoes", "shoes", (5, 19), ['sporty'], ['white']),
    ClothingItem("brown running shoes", "shoes", (5, 19), ['sporty'], ['brown']),
    ClothingItem("white light sweatshirt", "top", (20, 27), ['sporty'], ['white']),
    ClothingItem("beige light sweatshirt", "top", (20, 27), ['sporty'], ['beige']),
    ClothingItem("cream light sweatshirt", "top", (20, 27), ['sporty'], ['cream']),
    ClothingItem("light grey light sweatshirt", "top", (20, 27), ['sporty'], ['light grey']),
    ClothingItem("sky blue light sweatshirt", "top", (20, 27), ['sporty'], ['sky blue']),
    ClothingItem("black light sweatshirt", "top", (20, 27), ['sporty'], ['black']),
    ClothingItem("navy light sweatshirt", "top", (20, 27), ['sporty'], ['navy']),
    ClothingItem("charcoal light sweatshirt", "top", (20, 27), ['sporty'], ['charcoal']),
    ClothingItem("dark brown light sweatshirt", "top", (20, 27), ['sporty'], ['dark brown']),
    ClothingItem("deep green light sweatshirt", "top", (20, 27), ['sporty'], ['deep green']),
    ClothingItem("beige joggers", "bottom", (20, 27), ['sporty'], ['beige']),
    ClothingItem("black joggers", "bottom", (20, 27), ['sporty'], ['black']),
    ClothingItem("navy joggers", "bottom", (20, 27), ['sporty'], ['navy']),
    ClothingItem("black trainers", "shoes", (20, 27), ['sporty'], ['black']),
    ClothingItem("white trainers", "shoes", (20, 27), ['sporty'], ['white']),
    ClothingItem("brown trainers", "shoes", (20, 27), ['sporty'], ['brown']),
    ClothingItem("white sport tank", "top", (28, 40), ['sporty'], ['white']),
    ClothingItem("beige sport tank", "top", (28, 40), ['sporty'], ['beige']),
    ClothingItem("cream sport tank", "top", (28, 40), ['sporty'], ['cream']),
    ClothingItem("light grey sport tank", "top", (28, 40), ['sporty'], ['light grey']),
    ClothingItem("sky blue sport tank", "top", (28, 40), ['sporty'], ['sky blue']),
    ClothingItem("black sport tank", "top", (28, 40), ['sporty'], ['black']),
    ClothingItem("navy sport tank", "top", (28, 40), ['sporty'], ['navy']),
    ClothingItem("charcoal sport tank", "top", (28, 40), ['sporty'], ['charcoal']),
    ClothingItem("dark brown sport tank", "top", (28, 40), ['sporty'], ['dark brown']),
    ClothingItem("deep green sport tank", "top", (28, 40), ['sporty'], ['deep green']),
    ClothingItem("beige light jogger shorts", "bottom", (28, 40), ['sporty'], ['beige']),
    ClothingItem("black light jogger shorts", "bottom", (28, 40), ['sporty'], ['black']),
    ClothingItem("navy light jogger shorts", "bottom", (28, 40), ['sporty'], ['navy']),
    ClothingItem("black trainers", "shoes", (28, 40), ['sporty'], ['black']),
    ClothingItem("white trainers", "shoes", (28, 40), ['sporty'], ['white']),
    ClothingItem("brown trainers", "shoes", (28, 40), ['sporty'], ['brown']),
    ClothingItem("white wool coat", "top", (5, 19), ['minimal'], ['white']),
    ClothingItem("beige wool coat", "top", (5, 19), ['minimal'], ['beige']),
    ClothingItem("cream wool coat", "top", (5, 19), ['minimal'], ['cream']),
    ClothingItem("light grey wool coat", "top", (5, 19), ['minimal'], ['light grey']),
    ClothingItem("sky blue wool coat", "top", (5, 19), ['minimal'], ['sky blue']),
    ClothingItem("black wool coat", "top", (5, 19), ['minimal'], ['black']),
    ClothingItem("navy wool coat", "top", (5, 19), ['minimal'], ['navy']),
    ClothingItem("charcoal wool coat", "top", (5, 19), ['minimal'], ['charcoal']),
    ClothingItem("dark brown wool coat", "top", (5, 19), ['minimal'], ['dark brown']),
    ClothingItem("deep green wool coat", "top", (5, 19), ['minimal'], ['deep green']),
    ClothingItem("beige slim pants", "bottom", (5, 19), ['minimal'], ['beige']),
    ClothingItem("black slim pants", "bottom", (5, 19), ['minimal'], ['black']),
    ClothingItem("navy slim pants", "bottom", (5, 19), ['minimal'], ['navy']),
    ClothingItem("black chelsea boots", "shoes", (5, 19), ['minimal'], ['black']),
    ClothingItem("white chelsea boots", "shoes", (5, 19), ['minimal'], ['white']),
    ClothingItem("brown chelsea boots", "shoes", (5, 19), ['minimal'], ['brown']),
    ClothingItem("white plain shirt", "top", (20, 27), ['minimal'], ['white']),
    ClothingItem("beige plain shirt", "top", (20, 27), ['minimal'], ['beige']),
    ClothingItem("cream plain shirt", "top", (20, 27), ['minimal'], ['cream']),
    ClothingItem("light grey plain shirt", "top", (20, 27), ['minimal'], ['light grey']),
    ClothingItem("sky blue plain shirt", "top", (20, 27), ['minimal'], ['sky blue']),
    ClothingItem("black plain shirt", "top", (20, 27), ['minimal'], ['black']),
    ClothingItem("navy plain shirt", "top", (20, 27), ['minimal'], ['navy']),
    ClothingItem("charcoal plain shirt", "top", (20, 27), ['minimal'], ['charcoal']),
    ClothingItem("dark brown plain shirt", "top", (20, 27), ['minimal'], ['dark brown']),
    ClothingItem("deep green plain shirt", "top", (20, 27), ['minimal'], ['deep green']),
    ClothingItem("beige straight pants", "bottom", (20, 27), ['minimal'], ['beige']),
    ClothingItem("black straight pants", "bottom", (20, 27), ['minimal'], ['black']),
    ClothingItem("navy straight pants", "bottom", (20, 27), ['minimal'], ['navy']),
    ClothingItem("black leather sneakers", "shoes", (20, 27), ['minimal'], ['black']),
    ClothingItem("white leather sneakers", "shoes", (20, 27), ['minimal'], ['white']),
    ClothingItem("brown leather sneakers", "shoes", (20, 27), ['minimal'], ['brown']),
    ClothingItem("white linen shirt", "top", (28, 40), ['minimal'], ['white']),
    ClothingItem("beige linen shirt", "top", (28, 40), ['minimal'], ['beige']),
    ClothingItem("cream linen shirt", "top", (28, 40), ['minimal'], ['cream']),
    ClothingItem("light grey linen shirt", "top", (28, 40), ['minimal'], ['light grey']),
    ClothingItem("sky blue linen shirt", "top", (28, 40), ['minimal'], ['sky blue']),
    ClothingItem("black linen shirt", "top", (28, 40), ['minimal'], ['black']),
    ClothingItem("navy linen shirt", "top", (28, 40), ['minimal'], ['navy']),
    ClothingItem("charcoal linen shirt", "top", (28, 40), ['minimal'], ['charcoal']),
    ClothingItem("dark brown linen shirt", "top", (28, 40), ['minimal'], ['dark brown']),
    ClothingItem("deep green linen shirt", "top", (28, 40), ['minimal'], ['deep green']),
    ClothingItem("beige loose shorts", "bottom", (28, 40), ['minimal'], ['beige']),
    ClothingItem("black loose shorts", "bottom", (28, 40), ['minimal'], ['black']),
    ClothingItem("navy loose shorts", "bottom", (28, 40), ['minimal'], ['navy']),
    ClothingItem("black loafers", "shoes", (28, 40), ['minimal'], ['black']),
    ClothingItem("white loafers", "shoes", (28, 40), ['minimal'], ['white']),
    ClothingItem("brown loafers", "shoes", (28, 40), ['minimal'], ['brown']),
    ClothingItem("white knit sweater", "top", (5, 19), ['cute'], ['white']),
    ClothingItem("beige knit sweater", "top", (5, 19), ['cute'], ['beige']),
    ClothingItem("cream knit sweater", "top", (5, 19), ['cute'], ['cream']),
    ClothingItem("light grey knit sweater", "top", (5, 19), ['cute'], ['light grey']),
    ClothingItem("sky blue knit sweater", "top", (5, 19), ['cute'], ['sky blue']),
    ClothingItem("black knit sweater", "top", (5, 19), ['cute'], ['black']),
    ClothingItem("navy knit sweater", "top", (5, 19), ['cute'], ['navy']),
    ClothingItem("charcoal knit sweater", "top", (5, 19), ['cute'], ['charcoal']),
    ClothingItem("dark brown knit sweater", "top", (5, 19), ['cute'], ['dark brown']),
    ClothingItem("deep green knit sweater", "top", (5, 19), ['cute'], ['deep green']),
    ClothingItem("beige tweed skirt", "bottom", (5, 19), ['cute'], ['beige']),
    ClothingItem("black tweed skirt", "bottom", (5, 19), ['cute'], ['black']),
    ClothingItem("navy tweed skirt", "bottom", (5, 19), ['cute'], ['navy']),
    ClothingItem("black ankle boots", "shoes", (5, 19), ['cute'], ['black']),
    ClothingItem("white ankle boots", "shoes", (5, 19), ['cute'], ['white']),
    ClothingItem("brown ankle boots", "shoes", (5, 19), ['cute'], ['brown']),
    ClothingItem("white cardigan", "top", (20, 27), ['cute'], ['white']),
    ClothingItem("beige cardigan", "top", (20, 27), ['cute'], ['beige']),
    ClothingItem("cream cardigan", "top", (20, 27), ['cute'], ['cream']),
    ClothingItem("light grey cardigan", "top", (20, 27), ['cute'], ['light grey']),
    ClothingItem("sky blue cardigan", "top", (20, 27), ['cute'], ['sky blue']),
    ClothingItem("black cardigan", "top", (20, 27), ['cute'], ['black']),
    ClothingItem("navy cardigan", "top", (20, 27), ['cute'], ['navy']),
    ClothingItem("charcoal cardigan", "top", (20, 27), ['cute'], ['charcoal']),
    ClothingItem("dark brown cardigan", "top", (20, 27), ['cute'], ['dark brown']),
    ClothingItem("deep green cardigan", "top", (20, 27), ['cute'], ['deep green']),
    ClothingItem("beige A-line skirt", "bottom", (20, 27), ['cute'], ['beige']),
    ClothingItem("black A-line skirt", "bottom", (20, 27), ['cute'], ['black']),
    ClothingItem("navy A-line skirt", "bottom", (20, 27), ['cute'], ['navy']),
    ClothingItem("black oxford flats", "shoes", (20, 27), ['cute'], ['black']),
    ClothingItem("white oxford flats", "shoes", (20, 27), ['cute'], ['white']),
    ClothingItem("brown oxford flats", "shoes", (20, 27), ['cute'], ['brown']),
    ClothingItem("white frilled blouse", "top", (28, 40), ['cute'], ['white']),
    ClothingItem("beige frilled blouse", "top", (28, 40), ['cute'], ['beige']),
    ClothingItem("cream frilled blouse", "top", (28, 40), ['cute'], ['cream']),
    ClothingItem("light grey frilled blouse", "top", (28, 40), ['cute'], ['light grey']),
    ClothingItem("sky blue frilled blouse", "top", (28, 40), ['cute'], ['sky blue']),
    ClothingItem("black frilled blouse", "top", (28, 40), ['cute'], ['black']),
    ClothingItem("navy frilled blouse", "top", (28, 40), ['cute'], ['navy']),
    ClothingItem("charcoal frilled blouse", "top", (28, 40), ['cute'], ['charcoal']),
    ClothingItem("dark brown frilled blouse", "top", (28, 40), ['cute'], ['dark brown']),
    ClothingItem("deep green frilled blouse", "top", (28, 40), ['cute'], ['deep green']),
    ClothingItem("beige pleated skirt", "bottom", (28, 40), ['cute'], ['beige']),
    ClothingItem("black pleated skirt", "bottom", (28, 40), ['cute'], ['black']),
    ClothingItem("navy pleated skirt", "bottom", (28, 40), ['cute'], ['navy']),
    ClothingItem("black ballet flats", "shoes", (28, 40), ['cute'], ['black']),
    ClothingItem("white ballet flats", "shoes", (28, 40), ['cute'], ['white']),
    ClothingItem("brown ballet flats", "shoes", (28, 40), ['cute'], ['brown']),
    ClothingItem("white blazer", "top", (5, 19), ['business formal'], ['white']),
    ClothingItem("beige blazer", "top", (5, 19), ['business formal'], ['beige']),
    ClothingItem("cream blazer", "top", (5, 19), ['business formal'], ['cream']),
    ClothingItem("light grey blazer", "top", (5, 19), ['business formal'], ['light grey']),
    ClothingItem("sky blue blazer", "top", (5, 19), ['business formal'], ['sky blue']),
    ClothingItem("black blazer", "top", (5, 19), ['business formal'], ['black']),
    ClothingItem("navy blazer", "top", (5, 19), ['business formal'], ['navy']),
    ClothingItem("charcoal blazer", "top", (5, 19), ['business formal'], ['charcoal']),
    ClothingItem("dark brown blazer", "top", (5, 19), ['business formal'], ['dark brown']),
    ClothingItem("deep green blazer", "top", (5, 19), ['business formal'], ['deep green']),
    ClothingItem("beige wool slacks", "bottom", (5, 19), ['business formal'], ['beige']),
    ClothingItem("black wool slacks", "bottom", (5, 19), ['business formal'], ['black']),
    ClothingItem("navy wool slacks", "bottom", (5, 19), ['business formal'], ['navy']),
    ClothingItem("black leather shoes", "shoes", (5, 19), ['business formal'], ['black']),
    ClothingItem("white leather shoes", "shoes", (5, 19), ['business formal'], ['white']),
    ClothingItem("brown leather shoes", "shoes", (5, 19), ['business formal'], ['brown']),
    ClothingItem("white button-up shirt", "top", (20, 27), ['business formal'], ['white']),
    ClothingItem("beige button-up shirt", "top", (20, 27), ['business formal'], ['beige']),
    ClothingItem("cream button-up shirt", "top", (20, 27), ['business formal'], ['cream']),
    ClothingItem("light grey button-up shirt", "top", (20, 27), ['business formal'], ['light grey']),
    ClothingItem("sky blue button-up shirt", "top", (20, 27), ['business formal'], ['sky blue']),
    ClothingItem("black button-up shirt", "top", (20, 27), ['business formal'], ['black']),
    ClothingItem("navy button-up shirt", "top", (20, 27), ['business formal'], ['navy']),
    ClothingItem("charcoal button-up shirt", "top", (20, 27), ['business formal'], ['charcoal']),
    ClothingItem("dark brown button-up shirt", "top", (20, 27), ['business formal'], ['dark brown']),
    ClothingItem("deep green button-up shirt", "top", (20, 27), ['business formal'], ['deep green']),
    ClothingItem("beige slacks", "bottom", (20, 27), ['business formal'], ['beige']),
    ClothingItem("black slacks", "bottom", (20, 27), ['business formal'], ['black']),
    ClothingItem("navy slacks", "bottom", (20, 27), ['business formal'], ['navy']),
    ClothingItem("black oxfords", "shoes", (20, 27), ['business formal'], ['black']),
    ClothingItem("white oxfords", "shoes", (20, 27), ['business formal'], ['white']),
    ClothingItem("brown oxfords", "shoes", (20, 27), ['business formal'], ['brown']),
    ClothingItem("white light dress shirt", "top", (28, 40), ['business formal'], ['white']),
    ClothingItem("beige light dress shirt", "top", (28, 40), ['business formal'], ['beige']),
    ClothingItem("cream light dress shirt", "top", (28, 40), ['business formal'], ['cream']),
    ClothingItem("light grey light dress shirt", "top", (28, 40), ['business formal'], ['light grey']),
    ClothingItem("sky blue light dress shirt", "top", (28, 40), ['business formal'], ['sky blue']),
    ClothingItem("black light dress shirt", "top", (28, 40), ['business formal'], ['black']),
    ClothingItem("navy light dress shirt", "top", (28, 40), ['business formal'], ['navy']),
    ClothingItem("charcoal light dress shirt", "top", (28, 40), ['business formal'], ['charcoal']),
    ClothingItem("dark brown light dress shirt", "top", (28, 40), ['business formal'], ['dark brown']),
    ClothingItem("deep green light dress shirt", "top", (28, 40), ['business formal'], ['deep green']),
    ClothingItem("beige dress shorts", "bottom", (28, 40), ['business formal'], ['beige']),
    ClothingItem("black dress shorts", "bottom", (28, 40), ['business formal'], ['black']),
    ClothingItem("navy dress shorts", "bottom", (28, 40), ['business formal'], ['navy']),
    ClothingItem("black oxfords", "shoes", (28, 40), ['business formal'], ['black']),
    ClothingItem("white oxfords", "shoes", (28, 40), ['business formal'], ['white']),
    ClothingItem("brown oxfords", "shoes", (28, 40), ['business formal'], ['brown']),
    ClothingItem("white knit sweater", "top", (5, 19), ['smart casual'], ['white']),
    ClothingItem("beige knit sweater", "top", (5, 19), ['smart casual'], ['beige']),
    ClothingItem("cream knit sweater", "top", (5, 19), ['smart casual'], ['cream']),
    ClothingItem("light grey knit sweater", "top", (5, 19), ['smart casual'], ['light grey']),
    ClothingItem("sky blue knit sweater", "top", (5, 19), ['smart casual'], ['sky blue']),
    ClothingItem("black knit sweater", "top", (5, 19), ['smart casual'], ['black']),
    ClothingItem("navy knit sweater", "top", (5, 19), ['smart casual'], ['navy']),
    ClothingItem("charcoal knit sweater", "top", (5, 19), ['smart casual'], ['charcoal']),
    ClothingItem("dark brown knit sweater", "top", (5, 19), ['smart casual'], ['dark brown']),
    ClothingItem("deep green knit sweater", "top", (5, 19), ['smart casual'], ['deep green']),
    ClothingItem("beige dark chinos", "bottom", (5, 19), ['smart casual'], ['beige']),
    ClothingItem("black dark chinos", "bottom", (5, 19), ['smart casual'], ['black']),
    ClothingItem("navy dark chinos", "bottom", (5, 19), ['smart casual'], ['navy']),
    ClothingItem("black ankle boots", "shoes", (5, 19), ['smart casual'], ['black']),
    ClothingItem("white ankle boots", "shoes", (5, 19), ['smart casual'], ['white']),
    ClothingItem("brown ankle boots", "shoes", (5, 19), ['smart casual'], ['brown']),
    ClothingItem("white collared shirt", "top", (20, 27), ['smart casual'], ['white']),
    ClothingItem("beige collared shirt", "top", (20, 27), ['smart casual'], ['beige']),
    ClothingItem("cream collared shirt", "top", (20, 27), ['smart casual'], ['cream']),
    ClothingItem("light grey collared shirt", "top", (20, 27), ['smart casual'], ['light grey']),
    ClothingItem("sky blue collared shirt", "top", (20, 27), ['smart casual'], ['sky blue']),
    ClothingItem("black collared shirt", "top", (20, 27), ['smart casual'], ['black']),
    ClothingItem("navy collared shirt", "top", (20, 27), ['smart casual'], ['navy']),
    ClothingItem("charcoal collared shirt", "top", (20, 27), ['smart casual'], ['charcoal']),
    ClothingItem("dark brown collared shirt", "top", (20, 27), ['smart casual'], ['dark brown']),
    ClothingItem("deep green collared shirt", "top", (20, 27), ['smart casual'], ['deep green']),
    ClothingItem("beige chinos", "bottom", (20, 27), ['smart casual'], ['beige']),
    ClothingItem("black chinos", "bottom", (20, 27), ['smart casual'], ['black']),
    ClothingItem("navy chinos", "bottom", (20, 27), ['smart casual'], ['navy']),
    ClothingItem("black leather sneakers", "shoes", (20, 27), ['smart casual'], ['black']),
    ClothingItem("white leather sneakers", "shoes", (20, 27), ['smart casual'], ['white']),
    ClothingItem("brown leather sneakers", "shoes", (20, 27), ['smart casual'], ['brown']),
    ClothingItem("white polo shirt", "top", (28, 40), ['smart casual'], ['white']),
    ClothingItem("beige polo shirt", "top", (28, 40), ['smart casual'], ['beige']),
    ClothingItem("cream polo shirt", "top", (28, 40), ['smart casual'], ['cream']),
    ClothingItem("light grey polo shirt", "top", (28, 40), ['smart casual'], ['light grey']),
    ClothingItem("sky blue polo shirt", "top", (28, 40), ['smart casual'], ['sky blue']),
    ClothingItem("black polo shirt", "top", (28, 40), ['smart casual'], ['black']),
    ClothingItem("navy polo shirt", "top", (28, 40), ['smart casual'], ['navy']),
    ClothingItem("charcoal polo shirt", "top", (28, 40), ['smart casual'], ['charcoal']),
    ClothingItem("dark brown polo shirt", "top", (28, 40), ['smart casual'], ['dark brown']),
    ClothingItem("deep green polo shirt", "top", (28, 40), ['smart casual'], ['deep green']),
    ClothingItem("beige chino shorts", "bottom", (28, 40), ['smart casual'], ['beige']),
    ClothingItem("black chino shorts", "bottom", (28, 40), ['smart casual'], ['black']),
    ClothingItem("navy chino shorts", "bottom", (28, 40), ['smart casual'], ['navy']),
    ClothingItem("black loafers", "shoes", (28, 40), ['smart casual'], ['black']),
    ClothingItem("white loafers", "shoes", (28, 40), ['smart casual'], ['white']),
    ClothingItem("brown loafers", "shoes", (28, 40), ['smart casual'], ['brown']),
]

